### ISSUE TITLE
Login page positioning

### ISSUE THREAD

**Issue by thorbaert** [CodewarsClone/Codewars#54]
I've rebuilt with gulp probably 4 times and I get this on the login page.. It's not centered

![image](https://cloud.githubusercontent.com/assets/22752236/21432900/d5decabe-c82a-11e6-9f54-6ca3c3d44a85.png)

**Comment by SterlingChin** [comment]
Got it fixed.  I don't know why it wasn't reading the css file.  All fixed with my next push/pull request.

**Comment by SterlingChin** [comment]
I don't close this until we've verified that it's completed after the pull request
